name: Clang Format Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'src'
          - 'include'
          - 'resources'
    steps:
      - uses: actions/checkout@v4
      - name: Run Clang Format Check
        uses: jidicula/clang-format-action@v4.15.0
        with:
          clang-format-version: '20'
          check-path: ${{ matrix.path }}